/* Spoon: Receipt data clean-up (Prices tab, after Trends).

   Three numbers and a Clean up button. The button opens a sheet of cards, one
   per receipt product from the last 30 days that has something missing or
   doubtful. Answering a card uploads one small file to
   food/data/cleanup-answers/ in kave-hub; nothing else changes. A person
   reviews and applies those files later (apply_cleanup_answers.py), which is
   also when the card is deleted for good.

   Until then an answer can be undone from the Decisions tab, which deletes the
   file and brings the card back. After that the file is gone, so Undo finds
   nothing and says so. The queue itself is regenerated by build_cleanup_queue.py
   and only ever holds cards from the last 30 days. */
"use strict";

import { github } from "../github.js";
import { backSheets } from "./back-sheets.js";
import { bindSheetDrag } from "./sheet-price.js";
import { store } from "./store.js";
import { $, $$, escapeHtml } from "./util.js";

const LS_CLEANUP = "foodapp.cleanup";
const WINDOW_DAYS = 30;
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export const cleanup = {
  queue: null,       // the whole cleanup-queue.json
  queueEtag: null,
  remote: {},        // file -> { sha, path, answer }: answers on GitHub, not yet applied
  outbox: [],        // answers made here that have not reached GitHub yet
  drafts: {},        // file -> { ingredient_slug, new_ingredient, variant, pack_size, pen }
  skipped: [],       // files skipped this session, sent to the back of the pile
  tab: "todo",
  open: false,
};

function save() {
  try {
    localStorage.setItem(LS_CLEANUP, JSON.stringify({
      queue: cleanup.queue, queueEtag: cleanup.queueEtag,
      remote: cleanup.remote, outbox: cleanup.outbox,
    }));
  } catch (e) { /* storage full or blocked: the cache is optional */ }
}

export function loadCleanup() {
  try {
    const c = JSON.parse(localStorage.getItem(LS_CLEANUP));
    if (c) {
      cleanup.queue = c.queue || null;
      cleanup.queueEtag = c.queueEtag || null;
      cleanup.remote = c.remote || {};
      cleanup.outbox = Array.isArray(c.outbox) ? c.outbox : [];
    }
  } catch (e) { /* ignore corrupt cache */ }
}

/* ---- sync ---- */

let syncing = false;
export async function syncCleanup() {
  if (syncing || !github.hasToken()) return;
  syncing = true;
  try {
    const q = await github.getFile(github.config.cleanupQueuePath, { etag: cleanup.queueEtag });
    if (!q.notModified) { cleanup.queue = q.json; cleanup.queueEtag = q.etag; }

    const listing = await github.listDir(github.config.cleanupAnswersDir);
    const next = {};
    for (const f of listing) {
      if (!f.name.endsWith(".json")) continue;
      const key = f.name.slice(0, -5);
      const have = cleanup.remote[key];
      if (have && have.sha === f.sha) { next[key] = have; continue; }
      try {
        const r = await github.getFile(f.path);
        next[key] = { sha: f.sha, path: f.path, answer: r.json };
      } catch (e) { /* unreadable file: leave that card visible */ }
    }
    cleanup.remote = next;
    // anything in the outbox that has now reached GitHub is no longer waiting
    cleanup.outbox = cleanup.outbox.filter((a) => !next[a.file]);
    save();
    await flushOutbox();
  } finally {
    syncing = false;
    renderCleanup();
  }
}

let flushing = false;
async function flushOutbox() {
  if (flushing) return;
  flushing = true;
  try {
    for (const a of [...cleanup.outbox]) {
      const path = `${github.config.cleanupAnswersDir}/${escapeHtml(a.file)}.json`;
      let sha = null;
      try {
        const out = await github.putFile(path, a, null, `cleanup answer (${a.by || "?"}): ${a.item_raw}`);
        sha = out.sha;
      } catch (e) {
        if (e.gh === "offline") break;
        if (e.gh !== "http" && e.gh !== "conflict") throw e;
        // the file already exists (the other phone answered first): overwrite it
        const cur = await github.getFile(path);
        const out = await github.putFile(path, a, cur.sha, `cleanup answer (${a.by || "?"}): ${a.item_raw}`);
        sha = out.sha;
      }
      cleanup.remote[a.file] = { sha, path, answer: a };
      cleanup.outbox = cleanup.outbox.filter((x) => x.file !== a.file);
      save();
    }
  } catch (e) {
    console.warn("cleanup upload failed, will retry on the next sync:", e);
  } finally {
    flushing = false;
  }
}

/* ---- what is on screen ---- */

function today() { return new Date().toISOString().slice(0, 10); }
function daysAgo(dateStr) {
  const ms = new Date(today()) - new Date(dateStr);
  return Math.round(ms / 86400000);
}
function fmtDate(dateStr) {
  const [, m, d] = dateStr.split("-");
  return `${Number(d)} ${MONTHS[Number(m) - 1]}`;
}

function answered(file) {
  return !!cleanup.remote[file] || cleanup.outbox.some((a) => a.file === file);
}

// The queue is regenerated on a schedule, so it can be a few days old: drop a
// card whose newest receipt line has since slipped out of the 30-day window.
export function visibleCards() {
  if (!cleanup.queue) return [];
  const items = (cleanup.queue.items || []).filter((c) =>
    !answered(c.file) &&
    c.seen.some((s) => daysAgo(s.date) <= WINDOW_DAYS));
  const skipped = cleanup.skipped;
  return [...items.filter((c) => !skipped.includes(c.file)),
          ...items.filter((c) => skipped.includes(c.file))];
}

export function renderCleanup() {
  const q = cleanup.queue;
  const cards = visibleCards();
  const count = (m) => (q ? String(cards.filter((c) => c.missing.includes(m)).length) : "-");
  $("#cleanupNoIng").textContent = count("slug");
  $("#cleanupNoVar").textContent = count("variant");
  $("#cleanupNoPack").textContent = count("pack_size");
  const btn = $("#cleanupOpen");
  btn.textContent = q ? `See all · ${cards.length}` : "See all";
  btn.disabled = !q;
  if (cleanup.open) renderSheet();
}

/* ---- the sheet ---- */

let sheetHasHistory = false;

export function openCleanup() {
  if (!cleanup.queue) return;
  cleanup.open = true;
  cleanup.tab = "todo";
  const el = $("#cleanupSheet");
  el.hidden = false;
  el.classList.remove("shown");
  renderSheet();
  el.scrollTop = 0;
  void el.offsetHeight;
  el.classList.add("shown");
  try {
    history.pushState({ cleanupSheet: true }, "");
    sheetHasHistory = true;
  } catch (e) {
    sheetHasHistory = false;
  }
}

function hideSheet() {
  const el = $("#cleanupSheet");
  cleanup.open = false;
  el.classList.remove("shown");
  setTimeout(() => { if (!cleanup.open) el.hidden = true; }, 300);
}

// let the history entry do the closing so a tap, a swipe and back are one path
function requestClose() {
  if (sheetHasHistory) history.back();
  else hideSheet();
}

backSheets.push({
  isOpen: () => cleanup.open,
  close: () => { sheetHasHistory = false; hideSheet(); },
});

function chip(label, attrs, on = false, extra = "") {
  return `<button type="button" class="chip${on ? " on" : ""}${extra}" ${attrs}>${label}</button>`;
}

// What already exists for an ingredient, commonest first, from the history the
// queue carries: the sizes and variants a person is most likely to mean.
function optionsFor(field, slug, variant) {
  const h = (cleanup.queue && cleanup.queue.history) || [];
  const counts = new Map();
  const want = (row) => row[0] === slug && (field === "pack_size" && variant
    ? row[1] === variant : true);
  let rows = h.filter(want);
  if (field === "pack_size" && !rows.length) rows = h.filter((r) => r[0] === slug);
  for (const r of rows) {
    const v = field === "variant" ? r[1] : r[2];
    if (v && v !== "n/a") counts.set(v, (counts.get(v) || 0) + r[3]);
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1]).map((e) => e[0])
    .slice(0, field === "variant" ? 4 : 3);
}

function draftOf(file) {
  return cleanup.drafts[file] || (cleanup.drafts[file] = {});
}

function penOrChip(card, field, label) {
  const d = draftOf(card.file);
  if (d.pen === field) {
    return `<input class="pen-input" data-file="${escapeHtml(card.file)}" data-field="${field}" ` +
           `placeholder="${escapeHtml(label)}" autocomplete="off" autocapitalize="none">`;
  }
  return chip("✎", `data-act="pen" data-file="${escapeHtml(card.file)}" data-field="${field}"`, false, " pen");
}

function slugQuestion(card) {
  const d = draftOf(card.file);
  const sg = card.suggest || {};
  const chips = [];
  for (const s of sg.slug || []) {
    chips.push(chip(escapeHtml(s.replace(/-/g, " ")),
      `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="ingredient_slug" data-value="${escapeHtml(s)}"`,
      d.ingredient_slug === s));
  }
  if (sg.new_slug) {
    chips.push(chip(`Create “${escapeHtml(sg.new_slug)}”`,
      `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="new_ingredient" data-value="${escapeHtml(sg.new_slug)}"`,
      d.new_ingredient === sg.new_slug));
  }
  if (d.new_ingredient && d.new_ingredient !== sg.new_slug) {
    chips.push(chip(`Create “${escapeHtml(d.new_ingredient)}”`,
      `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="new_ingredient" data-value="${escapeHtml(d.new_ingredient)}"`, true));
  }
  if (d.ingredient_slug && !(sg.slug || []).includes(d.ingredient_slug)) {
    chips.push(chip(escapeHtml(d.ingredient_slug.replace(/-/g, " ")),
      `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="ingredient_slug" data-value="${escapeHtml(d.ingredient_slug)}"`, true));
  }
  chips.push(penOrChip(card, "slug", "ingredient"));
  return `<div class="ask">Which ingredient is this?</div><div class="chips">${chips.join("")}</div>`;
}

function variantQuestion(card) {
  const d = draftOf(card.file);
  const slug = d.ingredient_slug || card.current.ingredient_slug;
  const labels = (cleanup.queue && cleanup.queue.variant_labels) || {};
  const opts = slug ? optionsFor("variant", slug) : [];
  const chips = opts.map((v) => chip(escapeHtml(labels[v] || v),
    `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="variant" data-value="${escapeHtml(v)}"`,
    d.variant === v));
  chips.push(chip("n/a", `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="variant" data-value="n/a"`,
    d.variant === "n/a"));
  if (d.variant && d.variant !== "n/a" && !opts.includes(d.variant)) {
    chips.push(chip(escapeHtml(d.variant), `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="variant" data-value="${escapeHtml(d.variant)}"`, true));
  }
  chips.push(penOrChip(card, "variant", "variant"));
  return `<div class="ask">Which kind?</div><div class="chips">${chips.join("")}</div>`;
}

function packQuestion(card) {
  const d = draftOf(card.file);
  const slug = d.ingredient_slug || card.current.ingredient_slug;
  const variant = (d.variant && d.variant !== "n/a" ? d.variant : "") || card.current.variant;
  const opts = slug ? optionsFor("pack_size", slug, variant) : [];
  const chips = opts.map((v) => chip(escapeHtml(v),
    `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="pack_size" data-value="${escapeHtml(v)}"`,
    d.pack_size === v));
  if (d.pack_size && !opts.includes(d.pack_size)) {
    chips.push(chip(escapeHtml(d.pack_size), `data-act="pick" data-file="${escapeHtml(card.file)}" data-field="pack_size" data-value="${escapeHtml(d.pack_size)}"`, true));
  }
  chips.push(penOrChip(card, "pack_size", "e.g. 250 g or 6 x 56 g"));
  return `<div class="ask">Pack size</div><div class="chips">${chips.join("")}</div>`;
}

const TAGS = {
  slug: "no ingredient", variant: "no variant", pack_size: "no pack size",
  product: "no product name", unconfirmed: "unconfirmed", rule: "not in the rules yet",
};

function cardReady(card) {
  const d = draftOf(card.file);
  if (d.ingredient_slug || d.new_ingredient || d.variant || d.pack_size) return true;
  const onlyConfirm = card.missing.length === 1 && card.missing[0] === "unconfirmed";
  return onlyConfirm && d.confirmed;
}

function cardHtml(card) {
  const d = draftOf(card.file);
  const last = card.seen.map((s) => s.date).sort().pop();
  const n = card.seen.length;
  const cur = card.current;
  const known = [cur.ingredient_slug, cur.variant, cur.pack_size].filter(Boolean).join(" · ");
  const asks = [];
  if (card.missing.includes("slug")) asks.push(slugQuestion(card));
  if (card.missing.includes("variant")) asks.push(variantQuestion(card));
  if (card.missing.includes("pack_size")) asks.push(packQuestion(card));
  if (card.missing.length === 1 && card.missing[0] === "unconfirmed") {
    asks.push(`<div class="ask">Is this right?</div><div class="chips">` +
      chip("Yes, it is", `data-act="confirm" data-file="${escapeHtml(card.file)}"`, !!d.confirmed) + `</div>`);
  }
  const tags = card.missing.map((m) => `<span class="tag">${TAGS[m] || m}</span>`).join("");
  return `<div class="cu-card" data-file="${escapeHtml(card.file)}">` +
    `<div class="cu-raw">${escapeHtml(card.store)} · ${fmtDate(last)}${n > 1 ? ` · ${n} lines this month` : ""}</div>` +
    `<div class="cu-name">${escapeHtml(cur.product || card.item_normalised || card.item_raw)}</div>` +
    `<div class="cu-meta">Printed as “${escapeHtml(card.item_raw)}”${known ? ` · ${escapeHtml(known)}` : ""}</div>` +
    `<div class="cu-tags">${tags}</div>` +
    asks.join("") +
    `<div class="cu-foot"><button type="button" class="cu-quiet" data-act="skip" data-file="${escapeHtml(card.file)}">Skip</button>` +
    `<button type="button" class="cu-quiet" data-act="ignore" data-file="${escapeHtml(card.file)}">Ignore</button>` +
    `<button type="button" class="cu-done" data-act="done" data-file="${escapeHtml(card.file)}"${cardReady(card) ? "" : " disabled"}>Done</button></div>` +
    `</div>`;
}

function summarise(ans) {
  if (ans.ignore) return "Ignored";
  const parts = [];
  if (ans.ingredient_slug) parts.push(ans.ingredient_slug.replace(/-/g, " "));
  if (ans.new_ingredient) parts.push(`new ingredient “${ans.new_ingredient}”`);
  if (ans.variant) parts.push(ans.variant);
  if (ans.pack_size) parts.push(ans.pack_size);
  if (ans.confirmed && !parts.length) parts.push("confirmed as it was");
  return parts.join(" · ");
}

function decisions() {
  const all = [
    ...cleanup.outbox.map((a) => ({ a, waiting: true })),
    ...Object.values(cleanup.remote).map((r) => ({ a: r.answer, waiting: false })),
  ];
  return all.sort((x, y) => (y.a.at || "").localeCompare(x.a.at || ""));
}

function decisionsHtml() {
  const list = decisions();
  const note = `<p class="cu-note">Until it is processed overnight, an answer can be undone and the card comes back. After that it is final here; ask Claude to look at the history or change it.</p>`;
  if (!list.length) return note + `<p class="empty">Nothing waiting to be processed.</p>`;
  return note + list.map(({ a, waiting }) =>
    `<div class="cu-card"><div class="cu-raw">${escapeHtml(a.store)} · ${escapeHtml((a.by || "").trim() || "someone")}${waiting ? " · not uploaded yet" : ""}</div>` +
    `<div class="cu-name">${escapeHtml(a.item_normalised || a.item_raw)}</div>` +
    `<div class="cu-meta">${escapeHtml(summarise(a.answers || {}))}</div>` +
    `<div class="cu-foot"><span></span><span></span><button type="button" class="cu-done" data-act="undo" data-file="${escapeHtml(a.file)}">Undo</button></div></div>`
  ).join("");
}

function renderSheet() {
  const todo = visibleCards();
  const pending = decisions().length;
  $$("#cleanupTabs button").forEach((b) => {
    b.classList.toggle("on", b.dataset.tab === cleanup.tab);
    if (b.dataset.tab === "todo") b.textContent = `To do · ${todo.length}`;
    else b.textContent = `Decisions · ${pending}`;
  });
  $("#cleanupBody").innerHTML = cleanup.tab === "todo"
    ? (todo.length ? todo.map(cardHtml).join("") : `<p class="empty">Nothing left to clean up.</p>`)
    : decisionsHtml();
}

function rerenderCard(file) {
  const card = cleanup.queue.items.find((c) => c.file === file);
  const el = $(`.cu-card[data-file="${file}"]`, $("#cleanupBody"));
  if (!card || !el) return;
  el.outerHTML = cardHtml(card);
}

/* ---- answering ---- */

function submit(card, answers) {
  const a = {
    id: card.id, file: card.file, store: card.store, item_raw: card.item_raw,
    item_normalised: card.item_normalised, answers,
    by: store.state.settings.who || "", at: new Date().toISOString(),
  };
  cleanup.outbox.push(a);
  delete cleanup.drafts[card.file];
  save();
  renderCleanup();
  flushOutbox().then(() => { save(); renderCleanup(); });
}

function finish(card) {
  const d = draftOf(card.file);
  const answers = {};
  for (const k of ["ingredient_slug", "new_ingredient", "variant", "pack_size"]) if (d[k]) answers[k] = d[k];
  if (card.missing.includes("unconfirmed")) answers.confirmed = true;
  if (d.confirmed) answers.confirmed = true;
  submit(card, answers);
}

async function undo(file) {
  const r = cleanup.remote[file];
  if (!r) {
    cleanup.outbox = cleanup.outbox.filter((a) => a.file !== file);
    save();
    renderCleanup();
    return;
  }
  try {
    await github.deleteFile(r.path, r.sha, `cleanup answer undone: ${r.answer.item_raw}`);
  } catch (e) {
    if (e.gh !== "notFound") {
      console.warn("undo failed:", e);
      return;
    }
    // already gone: it was processed, so it can no longer be brought back
  }
  delete cleanup.remote[file];
  save();
  renderCleanup();
}

const KNOWN = () => new Set((cleanup.queue && cleanup.queue.known_slugs) || []);

function commitPen(input) {
  const { file, field } = input.dataset;
  const d = draftOf(file);
  const v = input.value.trim();
  d.pen = null;
  if (v) {
    if (field === "slug") {
      const slug = v.toLowerCase().replace(/\s+/g, "-");
      if (KNOWN().has(slug)) { d.ingredient_slug = slug; d.new_ingredient = ""; }
      else { d.new_ingredient = slug; d.ingredient_slug = ""; }
    } else if (field === "variant") d.variant = v.toLowerCase().replace(/\s+/g, "-");
    else d.pack_size = v;
  }
  rerenderCard(file);
}

export function wireCleanup() {
  $("#cleanupOpen").addEventListener("click", openCleanup);
  // tap or swipe down on the bar, or the back button: same as the other sheets
  bindSheetDrag("#cleanupBar", "#cleanupSheet", requestClose);
  $("#cleanupTabs").addEventListener("click", (e) => {
    const b = e.target.closest("button[data-tab]");
    if (!b) return;
    cleanup.tab = b.dataset.tab;
    renderSheet();
  });
  const body = $("#cleanupBody");
  body.addEventListener("click", (e) => {
    const b = e.target.closest("[data-act]");
    if (!b) return;
    const file = b.dataset.file;
    const card = cleanup.queue && cleanup.queue.items.find((c) => c.file === file);
    const d = draftOf(file);
    switch (b.dataset.act) {
      case "pick": {
        const f = b.dataset.field;
        // tapping the chosen chip again clears it
        if (d[f] === b.dataset.value) d[f] = "";
        else {
          d[f] = b.dataset.value;
          if (f === "ingredient_slug") d.new_ingredient = "";
          if (f === "new_ingredient") d.ingredient_slug = "";
        }
        rerenderCard(file);
        break;
      }
      case "confirm": d.confirmed = !d.confirmed; rerenderCard(file); break;
      case "pen": d.pen = b.dataset.field; rerenderCard(file);
        { const i = $(`.pen-input[data-file="${file}"]`, body); if (i) i.focus(); } break;
      case "skip":
        cleanup.skipped = [...cleanup.skipped.filter((f) => f !== file), file];
        renderSheet();
        break;
      case "ignore": if (card) submit(card, { ignore: true }); break;
      case "done": if (card && cardReady(card)) finish(card); break;
      case "undo": undo(file); break;
    }
  });
  body.addEventListener("keydown", (e) => {
    if (e.target.classList.contains("pen-input") && e.key === "Enter") {
      e.preventDefault();
      commitPen(e.target);
    }
  });
  body.addEventListener("focusout", (e) => {
    if (e.target.classList.contains("pen-input")) commitPen(e.target);
  });
  // leaving the Prices tab closes the sheet: it belongs to that tab
  store.subscribe((s) => {
    if (cleanup.open && s.view !== "prices") { sheetHasHistory = false; hideSheet(); }
  });
}
